# Generated by Django 2.2.1 on 2019-05-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('zona_barrio_uv_otro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Barrio UV Otro')),
                ('calle_avenida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle/Avenida')),
                ('dir_referencial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dir. Referencial')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero')),
                ('edificio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Edificio')),
                ('piso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Piso')),
                ('departamento_local_oficina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento Local Oficina')),
                ('longitud', models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitud')),
                ('latitud', models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitud')),
                ('servicio_id', models.IntegerField(unique=True, verbose_name='Servicio ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('zonauv', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zona Unidad Vecinal')),
                ('zonauv_codigo_zona_completo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zona Codigo completo')),
                ('zonauv_codigo_zona', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zona codigo')),
                ('zonauv_descr', models.TextField(blank=True, null=True, verbose_name='Zona UV descripcion')),
                ('zonauv_cod_adm', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zona Codigo Adm')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zona_municipio', to='direccion.Municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('marker', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marker')),
                ('marker_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Marker ID')),
                ('marker_position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marker Posicion')),
                ('marker_lat', models.CharField(blank=True, max_length=15, null=True, verbose_name='Marker Latitud')),
                ('marker_long', models.CharField(blank=True, max_length=15, null=True, verbose_name='Marker Longitud')),
                ('marker_visible', models.CharField(blank=True, max_length=10, null=True, verbose_name='Marker Visible')),
                ('marker_visible2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Marker Visible 2')),
                ('marker_drag', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marker Drag')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marker_zona', to='direccion.Zona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
