# Generated by Django 2.2.1 on 2019-05-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0002_direccion_marker_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nombre_facturacion', models.CharField(max_length=100, verbose_name='Nombre de Facturacion')),
                ('ci_nit', models.CharField(max_length=15, verbose_name='CI/NIT')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('urbano_rural', models.CharField(max_length=100, verbose_name='Urbano/Rural')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_departamento', to='direccion.Departamento')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_marker', to='direccion.Marker')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_municipio', to='direccion.Municipio')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_provincia', to='direccion.Provincia')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_zona', to='direccion.Zona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
