# Generated by Django 2.2.1 on 2019-05-02 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo Electrónico')),
                ('persona_id', models.CharField(max_length=25, unique=True, verbose_name='Nro. de Documento')),
                ('fecha_registro', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('is_active', models.BooleanField(default=False, verbose_name='Es Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Puede Logearse')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=80, verbose_name='Sidebar')),
                ('navbar', models.CharField(max_length=80, verbose_name='Navbar')),
                ('icon', models.CharField(max_length=20, verbose_name='Icono')),
                ('url_path', models.CharField(max_length=140, verbose_name='Url Path')),
                ('component', models.CharField(max_length=50, verbose_name='Componente')),
                ('orden', models.SmallIntegerField(verbose_name='Orden')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='seguridad.Menu', verbose_name='Padre')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='seguridad.Menu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
