# Generated by Django 2.2.1 on 2019-05-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('oficina', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('profesion', models.CharField(max_length=50, unique=True, verbose_name='Profesion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('tipodocumento', models.CharField(max_length=20, unique=True, verbose_name='Tipo de documento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('carnet', models.CharField(max_length=10, unique=True, verbose_name='Nro. CI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la persona')),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ap. paterno de la persona')),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ap. materno de la persona')),
                ('nacionalidad', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nacionalidad')),
                ('genero', models.CharField(max_length=10, verbose_name='Genero')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_cargo', to='personal.Cargo')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_oficina', to='personal.Oficina')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_profesion', to='personal.Profesion')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tipodocumento', to='personal.TipoDocumento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
